#JSON Format
var DATA = {
	"Monster" :
	[
		{
			"id": 1,
			"name": "Footman",
			"life_point" : 100,
			"max_life_point": 100,
			"rune": 2,
			"image" : "Footman.png", 
			"attack_type": "melee",
			"attack_power": 10,
			"affinity": ['E','M'],
			"ability": ['attack_up', '1'],
			"status": "Normal",
			"text": "This is Footman",
			"default_lp": 100,
		},
		{
			"id": 2,
			"name": "Archer",
			"life_point" : 100,
			"max_life_point": 100,
			"rune": 3,
			"image" : "Archer.png", 
			"attack_type": "range",
			"attack_power": 10,
			"affinity": ['E','M'],
			"ability": ['dot'],
			"status": "Normal",
			"text": "This is Archer",
			"default_lp": 100,
		},
		{
			"id": 3,
			"name": "SquadLeader",
			"life_point" : 100,
			"max_life_point": 100,
			"rune": 3,
			"image" : "SquadLeader.png",
			"attack_type": "execution",
			"attack_power": 10,
			"affinity": ['E','M'],
			"ability": ['attack_up'],
			"status": "Normal",
			"text": "This is SquadLeader",
		},
		{
			"id": 4,
			"name": "Guardian",
			"life_point" : 120,
			"max_life_point": 120,
			"rune": 3,
			"image" : "Guardian.png",
			"attack_type": "heal",
			"attack_power": 10,
			"affinity": ['E','M'],
			"ability": ['attack_up'],
			"status": "Normal",
			"text": "This is guardian",
		},
		{
			"id": 5,
			"name": "Mercenary",
			"life_point" : 150,
			"max_life_point": 150,
			"rune": 3,
			"image" : "Mercenary.png",
			"attack_type": "aoe",
			"attack_power": 10,
			"affinity": ['E','M'],
			"ability": ['attack_up'],
			"status": "Normal",
			"text": "This is merc",
		},
		{
			"id": 6,
			"name": "Mentor",
			"life_point" : 50,
			"max_life_point": 50,
			"rune": 0,
			"image" : "Mentor.png",
			"attack_type": "random",
			"attack_power": 30,
			"affinity": ['E','M'],
			"ability": ['attack_up'],
			"status": "Normal",
			"text": "This is Mentor",
		},
		
	]
}

