var DATA = {
	"Monster" :
	[
		{
		"id": 1,
		"name": "Odin",
		"life_point": 100,
		"max_life_point": 100,
		"rune": 5,
		"image": "odin.png",
		"attack_type": "challenger",
		"attack_power": 40,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Challenger - The chief of the gods in Norse mythology, known for his wisdom, knowledge, and magic."
	},
	{
		"id": 2,
		"name": "Thor",
		"life_point": 90,
		"max_life_point": 90,
		"rune": 4,
		"image": "thor.png",
		"attack_type": "salvo",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Salvo - God of thunder, strength, and fertility, known for his mighty hammer, Mjolnir."
	},
	{
		"id": 3,
		"name": "Loki",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 3,
		"image": "loki.png",
		"attack_type": "ranged",
		"attack_power": 25,
		"ability": ["attack_up"],
		"affinity": ["dot"],
		"status": "Normal",
		"text": "Ranged - God of mischief, trickery, and chaos who causes problems for the other gods."
	},
	{
		"id": 4,
		"name": "Freyja",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 3,
		"image": "freyja.png",
		"attack_type": "heal",
		"attack_power": 20,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Heal - Goddess of love, fertility, and war who associated with the Vanir."
	},
	{
		"id": 5,
		"name": "Freyr",
		"life_point": 50,
		"max_life_point": 50,
		"rune": 4,
		"image": "freyr.png",
		"attack_type": "aoe_heal",
		"attack_power": 30,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE Heal - God of fertility, prosperity, and sunlight. Brother of Freyja and a member of the Vanir clan."
	},
	{
		"id": 6,
		"name": "Hel",
		"life_point": 45,
		"max_life_point": 45,
		"rune": 2,
		"image": "hel.png",
		"attack_type": "execution",
		"attack_power": 30,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - Goddess of the underworld and ruler of the dead."
	},
	{
		"id": 7,
		"name": "Jormungandr",
		"life_point": 80,
		"max_life_point": 90,
		"rune": 6,
		"image": "jormungandr.png",
		"attack_type": "salvo",
		"attack_power": 60,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Salvo - Giant sea serpent who encircles the world, known as the Midgard Serpent."
	},
	{
		"id": 8,
		"name": "Fenrir",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 5,
		"image": "fenrir.png",
		"attack_type": "execution",
		"attack_power": 50,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - monstrous wolf who is destined to kill Odin during Ragnarok, the end of the world."
	},
	{
		"id": 9,
		"name": "Sleipnir",
		"life_point": 50,
		"max_life_point": 50,
		"rune": 1,
		"image": "sleipnir.png",
		"attack_type": "melee",
		"attack_power": 25,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Fastest and most agile horse in the world, who belongs to Odin."
	},
	{
		"id": 10,
		"name": "Valkyrie",
		"life_point": 75,
		"max_life_point": 75,
		"rune": 3,
		"image": "valkyrie.png",
		"attack_type": "ranged",
		"attack_power": 25,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - Group of female warriors who serve Odin and choose which warriors will go to Valhalla."
	},

		{
		"id": 11,
		"name": "Nidhogg",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 5,
		"image": "nidhogg.png",
		"attack_type": "melee",
		"attack_power": 70,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Dragon who gnaws on the roots of the World Tree, Yggdrasil."
	},
	{
		"id": 12,
		"name": "Heimdall",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 2,
		"image": "heimdall.png",
		"attack_type": "ranged",
		"attack_power": 25,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - Watchman of the gods who guards the rainbow bridge, Bifrost, that connects Asgard to Midgard."
	},
	{
		"id": 13,
		"name": "Skadi",
		"life_point": 50,
		"max_life_point": 50,
		"rune": 3,
		"image": "skadi.png",
		"attack_type": "challenger",
		"attack_power": 40,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Challenger - Goddess of winter, mountains, and hunting. Known for her beauty and hunting skills."
	},
	{
		"id": 14,
		"name": "Tyr",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 4,
		"image": "tyr.png",
		"attack_type": "aoe",
		"attack_power": 40,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE - God of law and justice who sacrificed his hand to bind the monstrous wolf Fenrir."
	},
	{
		"id": 15,
		"name": "Aegir",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 5,
		"image": "aegir.png",
		"attack_type": "execution",
		"attack_power": 55,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - God of the sea who often hosts parties for the gods and is known for his brewing skills."
	},
	{
		"id": 16,
		"name": "Ran",
		"life_point": 60,
		"max_life_point": 65,
		"rune": 2,
		"image": "ran.png",
		"attack_type": "heal",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Heal - Goddess of the sea who collects the drowned and brings them to her underwater realm."
	},
	{
		"id": 17,
		"name": "Mimir",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 2,
		"image": "mimir.png",
		"attack_type": "melee",
		"attack_power": 25,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Wise giant who was beheaded by the Vanir, whose head was preserved at one of three roots of tree world Yggdrasiln."
	},
	{
		"id": 18,
		"name": "Ymir",
		"life_point": 80,
		"max_life_point": 80,
		"rune": 5,
		"image": "ymir.png",
		"attack_type": "execution",
		"attack_power": 70,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - First giant who was created from melting ice and slain by Odin and his brothers Vili and Ve to create the world."
	},
#	{
#		"id": 19,
#		"name": "Surtr",
#		"life_point": 90,
#		"max_life_point": 90,
#		"rune": 7,
#		"image": "surtr.png",
#		"attack_type": "salvo",
#		"attack_power": 55,
#		"affinity": ["dot"],
#		"ability": ["attack_up"],
#		"status": "Normal",
#		"text": "Salvo - Giant who will lead the forces of Muspell during Ragnarok and burn the world with his sword."
#	},
	{
		"id": 20,
		"name": "Huginn and Muninn",
		"life_point": 35,
		"max_life_point": 35,
		"rune": 2,
		"image": "huginnandmuninn.png",
		"attack_type": "ranged",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - Odin's two ravens who fly around the world and bring him information."
	},
		{
		"id": 21,
		"name": "Gullveig",
		"life_point": 100,
		"max_life_point": 100,
		"rune": 5,
		"image": "gullveig.png",
		"attack_type": "challenger",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Challenger - Goddess who was burned three times by the gods but survived and became associated with gold and wealth."
	},
	{
		"id": 22,
		"name": "Idunn",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 2,
		"image": "idunn.png",
		"attack_type": "aoe_heal",
		"attack_power": 25,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE  Heal - Goddess of youth who was responsible for keeping the apples that give the gods eternal youth."
	},
	{
		"id": 23,
		"name": "Ratatoskr",
		"life_point": 50,
		"max_life_point": 50,
		"rune": 2,
		"image": "ratatoskr.png",
		"attack_type": "melee",
		"attack_power": 40,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Squirrel who runs up and down the World Tree, spreading gossip between the eagle at the top."
	},
	{
		"id": 24,
		"name": "Eir",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 6,
		"image": "eir.png",
		"attack_type": "aoe_heal",
		"attack_power": 60,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE Heal - Goddess of healing who was known for her skill in medicine and was often invoked by those in need of healing."
	},
	{
		"id": 25,
		"name": "Norns",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 5,
		"image": "norns.png",
		"attack_type": "execution",
		"attack_power": 60,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - One of the three most important goddest sisters of destiny: Urd, Verdandi, and Skuld."
	},
	{
		"id": 26,
		"name": "Bragi",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 4,
		"image": "bragi.png",
		"attack_type": "challenger",
		"attack_power": 65,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Challenger - God of poetry and eloquence who was known for his smooth talking."
	},
	{
		"id": 27,
		"name": "Forseti",
		"life_point": 45,
		"max_life_point": 45,
		"rune": 2,
		"image": "forseti.png",
		"attack_type": "melee",
		"attack_power": 40,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - God of justice and peace who was known for his fair judgements."
	},
	{
		"id": 28,
		"name": "Vidar",
		"life_point": 75,
		"max_life_point": 75,
		"rune": 5,
		"image": "vidar.png",
		"attack_type": "ranged",
		"attack_power": 60,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - Son of Odin, silent god who avenges his father's death by killing the wolf Fenrir at Ragnarok."
	},
	{
		"id": 29,
		"name": "Ullr",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 3,
		"image": "ullr.png",
		"attack_type": "ranged",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - God of archery, skiing, and hunting who was often worshipped by hunters and warriors."
	},
	{
		"id": 30,
		"name": "Garmr",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 3,
		"image": "garmr.png",
		"attack_type": "ranged",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - Giant dog who guarded the entrance to the underworld and would let the dead in but not allow living comeby."
	},
		{
		"id": 31,
		"name": "Sigyn",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 4,
		"image": "sigyn.png",
		"attack_type": "heal",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Heal - Wife of Loki."
	},
	{
		"id": 32,
		"name": "Hoenir",
		"life_point": 50,
		"max_life_point": 50,
		"rune": 2,
		"image": "hoenir.png",
		"attack_type": "salvo",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Salvo - Shadowy god and companion of Odin and Loki on a couple of occasions in the old texts."
	},
	{
		"id": 33,
		"name": "Var",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 2,
		"image": "var.png",
		"attack_type": "challenger",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Challenger - Goddess of oaths and agreements who was invoked during legal proceedings."
	},
	{
		"id": 34,
		"name": "Kvasir",
		"life_point": 45,
		"max_life_point": 45,
		"rune": 1,
		"image": "kvasir.png",
		"attack_type": "melee",
		"attack_power": 55,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - God of wisdom who was created from the saliva of the gods and was known for his cleverness."
	},
	{
		"id": 35,
		"name": "Alfar",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 4,
		"image": "alfar.png",
		"attack_type": "aoe_heal",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE Heal - Elves who were believed to be minor gods associated with nature and magic."
	},
	{
		"id": 36,
		"name": "Draugr",
		"life_point": 75,
		"max_life_point": 75,
		"rune": 4,
		"image": "draugr.png",
		"attack_type": "ranged",
		"attack_power": 55,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - Undead creatures who protected their treasure and were feared by the living."
	},
	{
		"id": 37,
		"name": "Aesir",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 2,
		"image": "aesir.png",
		"attack_type": "ranged",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - The main clan of gods of Norse Mythology who were associated with war, strength, and courage."
	},
	{
		"id": 38,
		"name": "Huldra",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 3,
		"image": "huldra.png",
		"attack_type": "aoe",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE - Female creature with a tail and cow-like ears who lived in the forest and lured men into danger."
	},
	{
		"id": 39,
		"name": "Ask and Embla",
		"life_point": 100,
		"max_life_point": 100,
		"rune": 8,
		"image": "askandembla.png",
		"attack_type": "aoe",
		"attack_power": 40,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE - First man and woman in Norse Mythology who were created from two pieces of driftwood by Odin, Vili, and Ve."
	},
	{
		"id": 40,
		"name": "Berserker",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 3,
		"image": "berserker.png",
		"attack_type": "melee",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Warriors who fought with reckless abandon and were said to enter a trance-like state during battle."
	},
	{
		"id": 41,
		"name": "Lindworm",
		"life_point": 85,
		"max_life_point": 85,
		"rune": 5,
		"image": "lindworm.png",
		"attack_type": "execution",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - Dragon with two legs and a long, serpent-like body who was known for its venomous bite."
	},
	{
		"id": 42,
		"name": "Mara",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 4,
		"image": "mara.png",
		"attack_type": "challenger",
		"attack_power": 34,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Challenger - Female spirit who visited people in their sleep and caused nightmares."
	},
	{
		"id": 43,
		"name": "Neck",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 2,
		"image": "neck.png",
		"attack_type": "execution",
		"attack_power": 40,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - Water spirit who played beautiful music and lured sailors to their death."
	},
	{
		"id": 44,
		"name": "Tomte",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 2,
		"image": "tomte.png",
		"attack_type": "melee",
		"attack_power": 30,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - The household spirit who protected the home and farm animals."
	},
	{
		"id": 45,
		"name": "Baldr",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 3,
		"image": "baldr.png",
		"attack_type": "ranged",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - The god of light and purity who was loved by all the gods except Loki, who plotted his death."
	},
	{
		"id": 46,
		"name": "Vatnavaettir",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 3,
		"image": "vatnavaettir.png",
		"attack_type": "heal",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Heal - Water spirits who were associated with rivers, lakes, and the sea."
	},
	{
		"id": 47,
		"name": "Alsvin",
		"life_point": 50,
		"max_life_point": 50,
		"rune": 1,
		"image": "alsvin.png",
		"attack_type": "melee",
		"attack_power": 30,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - One of the two horses who pulled the chariot of the sun goddess Sol."
	},
	{
		"id": 48,
		"name": "Askafroa",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 4,
		"image": "askafroa.png",
		"attack_type": "aoe_heal",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "AOE Heal - Female spirit who guarded the ash tree and was believed to have the power to heal."
	},
	{
		"id": 49,
		"name": "Audumbla",
		"life_point": 50,
		"max_life_point": 50,
		"rune": 1,
		"image": "audumbla.png",
		"attack_type": "melee",
		"attack_power": 35,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Primaeval cow who licked the ice to create the first god, Buri."
	},
	{
		"id": 50,
		"name": "Dvalin",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 2,
		"image": "dvalin.png",
		"attack_type": "ranged",
		"attack_power": 30,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - Dwarf who helped create the magic golden boar Gullinbursti."
	},
	{
		"id": 51,
		"name": "Einherjar",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 4,
		"image": "einherjar.png",
		"attack_type": "challenger",
		"attack_power": 50,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Challenger - The brave warriors who were chosen to be soldiers of midgard."
	},
	{
		"id": 52,
		"name": "Fafnir",
		"life_point": 65,
		"max_life_point": 65,
		"rune": 4,
		"image": "fafnir.png",
		"attack_type": "melee",
		"attack_power": 50,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Giant who turned into a dragon and guarded a hoard of gold."
	},
	{
		"id": 53,
		"name": "Gandalf",
		"life_point": 55,
		"max_life_point": 55,
		"rune": 2,
		"image": "gandalf.png",
		"attack_type": "salvo",
		"attack_power": 30,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Salvo - Wise wizard who helped the gods and was associated with magic and wisdom."
	},
	{
		"id": 54,
		"name": "Helreginn",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 3,
		"image": "helreginn.png",
		"attack_type": "ranged",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Ranged - A giant who was killed by Thor's hammer."
	},
	{
		"id": 55,
		"name": "Dwarves",
		"life_point": 40,
		"max_life_point": 40,
		"rune": 1,
		"image": "dwarves.png",
		"attack_type": "melee",
		"attack_power": 30,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - Mythical creatures who were said to be master craftsmen and were associated with metalworking."
	},
	{
		"id": 56,
		"name": "Eikthyrnir",
		"life_point": 60,
		"max_life_point": 60,
		"rune": 2,
		"image": "eikthyrnir.png",
		"attack_type": "salvo",
		"attack_power": 25,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Salvo - The stag who stood on top of Valhalla and ate from the branches of Yggdrasil."
	},
	{
		"id": 57,
		"name": "Kari",
		"life_point": 75,
		"max_life_point": 75,
		"rune": 4,
		"image": "kari.png",
		"attack_type": "execution",
		"attack_power": 45,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Execution - God of wind who was known for his strength and speed."
	},
	{
		"id": 58,
		"name": "Sif",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 4,
		"image": "sif.png",
		"attack_type": "heal",
		"attack_power": 55,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Heal - Goddess of fertility and agriculture who was Thor's wife and had golden hair."
	},
	{
		"id": 59,
		"name": "Sigurd",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 4,
		"image": "sigurd.png",
		"attack_type": "heal",
		"attack_power": 55,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Heal - A legendary hero who killed a dragon Fafnir."
	},
	{
		"id": 60,
		"name": "Vali",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 4,
		"image": "vali.png",
		"attack_type": "melee",
		"attack_power": 55,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "Melee - The son of Odin who was born to avenge Balder's death and kill Hod."
	},
	{
		"id": 61,
		"name": "Vanir",
		"life_point": 70,
		"max_life_point": 70,
		"rune": 4,
		"image": "vanir.png",
		"attack_type": "execution",
		"attack_power": 55,
		"affinity": ["dot"],
		"ability": ["attack_up"],
		"status": "Normal",
		"text": "execution - The clan of gods in Norse mythology who were associated with fertility, prosperity, and magic."
	},
]}
